### ISSUE TITLE
메모용

### ISSUE THREAD

**Issue by junha-ahn** [junha-ahn/kotlin-boot-deployment#16]
## 대기열 작업 Follow up 가이드

https://github.com/f-lab-clone/queuing-system

첫번째 [PR](https://github.com/f-lab-clone/queuing-system/pull/2) 을 통해 대기열 티켓을 발행하는 API 서버를 만들었습니다.
- 테스트 파일: [ticket.spec.js](https://github.com/f-lab-clone/queuing-system/pull/2/files#diff-44b01e283fd5241ce8d7b80157868f96872be44018799955361125c9a55a2d9e)
- 컨트롤러 파일: [ticket.js](https://github.com/f-lab-clone/queuing-system/pull/2/files#diff-c264d5d91f45a22090900a6dd609c6ca5582f1a9742b2699201f340824ea06d1)
- 서비스 + 레포지토리 레이어 파일: [ticketStore.js](https://github.com/f-lab-clone/queuing-system/pull/2/files#diff-4eba5b9746ae05144d07e20cd18cf7a9808d174192ae3d75ea1fad777a234c9f)

> Nodejs가 익숙치 않다면 주요 체크 파일만 봐도 충분합니다.

두번째 [PR](https://github.com/f-lab-clone/queuing-system/pull/5)을 통해 발행된 대기열 티켓(=Wating)을 입장시키는(Move into Running) 스케줄러를 개발했습니다.
- 테스트파일: [jobService.spec.js](https://github.com/f-lab-clone/queuing-system/pull/5/files#diff-0ecbb389826a78ce7f08e273cd6c49d25cc667e765db2e23b38a692b123a55b5)
- 서비스 레이어 파일: [jobService.js](https://github.com/f-lab-clone/queuing-system/pull/5/files#diff-d09c631f8f72640df09cd73c29678a4d919834754c0293303b1dbe45429b850a)
- 스케줄러 파일: [job.js](https://github.com/f-lab-clone/queuing-system/pull/5/files#diff-de3d2ed3e87fe602a9f9428b16ee0a4630bddd948ad86ff307e5ff8bef1735b7)

현재 AWS `development` 환경에 배포 완료되었습니다. (물런 리뷰가 발생한다면, 수정해야겠지만요)
- https://github.com/f-lab-clone/ticketing-infra/issues/80 이슈를 통해 확인 가능

## Todo

전체적으로 하단에 기재된 Todo List를 따라가시면됩니다.

### 박정섭
- [ ] 대기열 PR 리뷰 
- [ ] 김민준 수병 작업 Follow up : [remove-total-count](https://github.com/f-lab-clone/ticketing-backend/pull/124), [sort-with-querydsl](https://github.com/f-lab-clone/ticketing-backend/pull/125) (**작업중**)
  - 이슈도 같이 읽어주세요 (아마 참고 링크가 있을겁니다)
- [ ] [API Docs 정상화](https://github.com/f-lab-clone/ticketing-backend/issues/115)

### 김민준
- [ ] [sort-with-querydsl](https://github.com/f-lab-clone/ticketing-backend/pull/125) 마무리

### 임하영
- [ ] 대기열 PR 리뷰

----

만약 다 하셨다면 크게 세가지 루트가 있을 것 같습니다.
1. 잔여 이슈 중 마음에 드는 것 처리
    - 백엔드에서는 [Reservation 이전 대기열 체크 로직 도입](https://github.com/f-lab-clone/ticketing-backend/issues/126)이 가장 중요한 이슈겠네요
2. 직접 K6 테스트해보기 (아래 `성능테스트 Follow up 가이드` 작성해놨으니 임하영수병님과 함께 따라해보세요~)
3. **Database 도서 학습** 
    - 추천: Real MySQL 8.0 (바이블)
    - 추천: [업무에 바로 쓰는 SQL 튜닝](https://devkly.com/book/sql-turing/) (빠르게 필요한 부분만 읽어낼 수 있음)
    - 이 외에도 "SQL 튜닝, 인덱스, 실행계획" 등의 키워드가 포함된 책이면 자유롭게 읽어서 학습해보세요.

## 성능테스트 Follow up 가이드

현재 진행한 두가지 스파이크 테스트
- [인터파크 0.001% 스파이크 테스트](https://github.com/f-lab-clone/ticketing-backend/issues/99)
- [SignIn 스파이크 테스트](https://github.com/f-lab-clone/ticketing-backend/issues/105) [완료]

실제로 어떻게 진행할 수 있을까?
- [kubectl 사용법](https://github.com/f-lab-clone/ticketing-infra/wiki/kubctl-%EC%82%AC%EC%9A%A9%EB%B2%95) 을 통해 가이드를 읽는다
- 임하영 수병님과 손잡고 사지방가서 3명이서 한 1시간만 투자하면 될듯? 같이 배워서 하나씩 만들어보세용
- 임하영수병님은 aws console 로그인 후 eksadmin (IAM User)의 key 발급해서 aws configure가능하게 해주시면 될듯요 
- 그 후 k6 어케하는지 설명 쭈욱

----

# 개인 메모용

## 2차 Spike Test 고려사항

**현재 API 고도화(Pagenation) 지연으로 실행 불가능**

Backend Pod 재실행 필요

```sh
kubectl delete replicaset <backend replica name>
```

하나의 이벤트에만 모든 트래픽이 몰려야한다.
- 특정 Event ID를 준비해두자.

K6 옵션 `noConnectionReuse` 사용

**Comment by junha-ahn** [comment]
이슈 
- Terraform rds secret manager get master password

**Comment by junha-ahn** [comment]
# 인쇄
## 알고리즘
- [ ] https://www.acmicpc.net/problem/1941
- [ ] https://www.acmicpc.net/problem/1939
- [ ] https://www.acmicpc.net/problem/1937
- [ ] https://www.acmicpc.net/problem/1600

## Helm
- https://helm.sh/ko/docs/chart_template_guide/getting_started/

**Comment by junha-ahn** [comment]
## 복지의 원리 - 양재진

복지의 탄생 
- 19세기 산업혁명시기 노동자가 소득활동을 하지 못할때, 참담함은 노예나 농노보다 못했다. 영국에서는(서민원등의 민주주의) 노동계급의 형성이나 운동의 발전으로 체제에 흡수되었지만 권위주의 독일은 겉으로는 강해보이지만 그만큼 한번에 부러질 가능성이 더 컸다. 
- 비스마르크는 당근과 채찍을 통해 체제를 지키고자 했다. 사회주의 탄압법을 제정하고, 복지를 통해 국가가 국민의 삶을 보호해줄 테니, 체제를 바꾼다고 혁명이다 뭐다 하지 말라는 것 
- > 결국 인권, 복지 모두 보편 계급의 사회적 생산능력, 조직력이 어느정도의 힘이나 위협을 발휘할때 등장

왜 지금도 유지되는가?
- 21세기의 노동자가 단결해 자본주의를 무너트릴까봐? 아니다 공적 사회보장 시스템의 지속은 그 자체의 합리성때문
- 공적연금은 <장수의 위험> 을 관리하는데 시장의 사적 연금보다 우수, 통계를 바탕으로 모든 병의 발병률, 수명을 예측한다. 국가가 개입한다고 무조건 효율적인건 아니지만...
- 탄생은 정치적, 100년 이상의 장수 비결은 자체의 합리성
- > 물런 국민연금이 결국 합리성을 바탕으로 유지되어야 하는 체제이나... 음... 고령화 저출산 사회에서 버틸 수 있을까? => 그래도 유지되어야 한다 => 근데 나는 안내면 => 이런 개인의 선택이 결국 통계적으로 망하는 길.. 쩝... 

복지국가는 거대한 이념적 지도 위에 하향식으로 건설되지 않았다. 주먹구구 식으로 밑에서부터 사회문제를 하나씩 해결해나가며 성장

권력자원론
- 복지 지출이 나라 별로 차이 나는 이유를 설명하기 위해 1980년대 등장 
- 임금 노동자의 정치적 힘이 클수록 복지국가가 발전한다 (우리나라 민주화로 노동권이 고양된 1987년 이후 한국 복지의 성장을 설명하는데 도움 - 그러나 반만 맞다)
- 한국 노동운동은 기업별 노조 형태를 띤다. 그래서 기업 울타리를 넘는 노동시장의 문제, 빈곤 등은 노사협상테이블에 올리지 못한다.

의료보험: OECD 중 병의원을 찾는 횟수가 압도적 1위, 소비지출에서 차지하는 의료비 본인부담금이 두번째로 높은 나라
- > 명암이네... 쩝 효율화를 어떻게하는지 책에서 설명

한국 노동시장은 조선시대 과거제를 통한 계급사회와 유사해지고 있다.
- 높은 등용문을 뚫으면, 현직에 있는 사람들의 실력은 평가하지 않고, 높은 인기 직군은 마치 성과 같다. 한번 들어가면 밖으로 쫓겨날 우려가 없다.

산업혁명 이후 엄청난 기계화와 자동화가 실현되었지만 실업자가 크게 늘지 않앗다.
- 심지어 한국의 실업률은 3.7%인 반면, 산업화 이전인 196년에 실업률은 34.2%다. 2019년 아프리카 나미비아의 실업률은 23.2%다 
- 왜그런가? 기계화와 자동화는 기업 및 산업 경쟁력을 강화시킨다. 연관 산업이 성장하고, 금융, 컨설팅 서비스업이 발달하고, 임금이 오르며 요식업, 레저 스포츠... 세입이 늘고
- 기본소득에 대해, 기술혁신으로 인한 일자리 변화가 예상되는 시점에서 국가가 할 일은 일자리 감소를 전제로 기본소득을 도입하는게 아니라, 변화에 적응할 수 있게 직업능력을 배양하고, 사회보장이라는 안전망을 보다 촘촘하고 후하게 까는 것이다. 
- 우리가 할 일은 기본소득국가 건설이 아니라, 혁신경제와 복지국가를 튼튼하게 만드는 것이다.

**Comment by junha-ahn** [comment]
## 프동프동 향후 계획

## 8.23
 일정             | 인프라 | 개발 | 프론트
-------- | -- | -- | --
08.21~08.27 | 모니터링 구축 <br/> ArgoCD & Helm & Config | API 기능 고도화 <br/> 대기열 시스템 설계 <br/>좌석 예매 | 리스트 페이지
08.28~09.03 | 성능 테스트 구축 |  | 무한 스크롤
09.04~09.10 <br/> - 5일 휴가 |   |   | 로그인/회원가입
09.11~09.18 <br/> - 4일 휴가 | 성능 테스트 진행 | 성능 테스트 진행 & 트러블 슈팅 | 이벤트 상세/마이페이지
09.18~09.24 <br/> - 5일 휴가 | 성능 테스트 자동화 <br/> 로그 파이프라인 구축 |   | 날짜/시간 선택
09.25~10.01 |   |   | 좌석 선택
10.02~10.08 |   |   |  

결국 중요한건 계속 파고들어가야 한다. 
- 특히 성능 개선부분이다. 
- 트러블 슈팅 파트가 가장 중요한 부분

## 8.28

 일정             | 인프라 | 개발 | 프론트
-------- | -- | -- | --
08.21~08.27 | 모니터링 구축 <br/> ArgoCD & Helm & Config| API 기능 고도화 <br/> 대기열 시스템 설계 <br/>좌석 예매 | 리스트 페이지
08.28~09.03 | (연장) |  | (연장 - FS야간)
09.04~09.10 <br/> - 5일 휴가 | 성능 테스트 구축  |   | 무한 스크롤
09.11~09.18 <br/> - 4일 휴가 | 성능 테스트 진행 | 성능 테스트 진행 & 트러블 슈팅 | 로그인/마이페이지
09.18~09.24 <br/> - 5일 휴가 | 성능 테스트 자동화 <br/> 로그 파이프라인 구축 |   | 이벤트 상세/마이페이지
09.25~10.01 |   |   | 날짜/시간 선택
10.02~10.08 |   |   | 좌석 선택
10.09~10.15 | | |
- 인프라 연장: 임하영 휴가
- 프론트 연장: 강성진 당직


## 9.5
 일정             | 인프라 | 개발 | 프론트
-------- | -- | -- | --
09.04~09.10 <br/> - 5일 휴가 | 모니터링 구축, 성능 테스트 구축 <br/> Secret 변경  | API 기능 고도화 <br/> 대기열 시스템 설계 <br/>좌석 예매   | 무한 스크롤
09.11~09.18 <br/> - 4일 휴가 |  |  | 로그인/마이페이지
09.18~09.24 <br/> - 5일 휴가 |  |**성능 테스트 & 개선** <br/>  대기열 구현  | 이벤트 상세/마이페이지
09.25~10.01 |   |   | 날짜/시간 선택
10.02~10.08 |   |   | 좌석 선택
10.09~10.15 <br/> - 전역 | | |


## 9.11
 일정             | 인프라 | 개발 | 프론트
-------- | -- | -- | --
09.11~09.18 <br/> - 4일 휴가 | 모니터링 구축, 성능 테스트 구축 <br/> ~~Secret~~, Nginx 변경 |  API 기능 고도화 <br/> 대기열 시스템 설계 <br/>좌석 예매 | 무한 스크롤
09.18~09.24 <br/> - 5일 휴가 |  |**성능 테스트 & 개선** <br/>  대기열 구현  | 로그인/마이페이지
09.25~10.01 |   |   | 이벤트 상세 페이지
10.02~10.08 |   |   | 날짜/시간 선택
10.09~10.15 <br/> - 전역 | |  좌석 선택 |


## 9.23
 일정             | 인프라 | 개발 
-------- | -- | -- 
09.25~10.01 |  성능테스트 연습 <br/> 구조 개선  |  API 기능 고도화
10.02~10.08 |   |  성능테스트&개선 <br/> 대기열 구현 
10.09~10.15 <br/> - 전역 | | |
10.16~10.22 | | |


## 10.2

 일정             | 인프라 | 개발 
-------- | -- | -- 
10.02~10.08 |  성능테스트&분석 |  성능테스트&개선 <br/> 대기열 구현 
10.09~10.15 <br/> - 전역 | | |
10.16~10.22 | | |


## 10.9

 일정             | 인프라 | 개발 
-------- | -- | -- 
10.09~10.15 |  성능테스트&분석 | 성능테스트&개선 <br/> 대기열 구현 
10.16~10.22 | | |

> 대기열 설계와 좌석 설계 두 마리 큰 토끼를 잡을 방법이 없을까?


## 10.12

<img width="225" alt="image" src="https://github.com/junha-ahn/kotlin-boot-deployment/assets/41976906/c0bba73d-f993-44d7-9d54-cb898fbb43a7">


 일정             | 인프라 | 개발 
-------- | -- | -- 
10.12~10.15 | 안준하: 전역+넉다운 | 잔여이슈 해결 |
10.16~10.22 | 성능 테스트 진행 | 대기열 구현 |
10.23~10.29 | 성능 테스트 진행 | 대기열 구현 |

**Comment by junha-ahn** [comment]
## 테스트 시나리오

### Test 고려사항

Backend Pod 재실행

Test Data Script


### [JVM Warm up](https://github.com/f-lab-clone/ticketing-infra/issues/41) 테스트

1. Backend ReplicaSet 전체 재실행 후 즉시 Spike Test
2. 3분 경과 후 동일 Spike Test 재시도 

성능 비교

**Comment by junha-ahn** [comment]
# EOF 이슈

<img width="986" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/cc359e6e-6f5c-487c-9b45-dc829d1cf9b6">

<img width="1088" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/a1f11519-91f1-4a55-a6e5-4bbafc2639ee">

<img width="618" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/ad4fd439-fe80-4214-8621-b4f9506f4a8c">


단순한 HealthCheck (VU 2000)에서도 발생하는 EOF 에 대해서 분석이 필요하다.

<img width="1710" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/58e27a87-0d88-4674-a75b-d4df34034247">
<img width="1704" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/db622abc-5e92-436b-97d2-3724ad451517">

**현재 대시보드로는 문제상황이 추측되지 않는다.**

원인 추측
- k8s network (socket...)
- nginx baremetal config

참고 할만 한 글
- https://community.grafana.com/t/getting-a-request-failed-eof-error/98695
- https://stackoverflow.com/questions/61076334/errors-shown-by-k6-when-reaching-a-bigger-number-of-virtual-users
